require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 25

Rails/SkipsModelValidations:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
